name: file-size-check

on:
  push:
  pull_request:

jobs:
  file-size-check:
    runs-on: ubuntu-latest
    name: check file sizes
    steps:
      - uses: actions/checkout@v3
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          ./tests/file-size-check.sh "{{ steps.files.outputs.all }}"
