name: file-size-check

on:
  pull_request:

jobs:
  file-size-check:
    runs-on: ubuntu-latest
    name: check file sizes
    steps:
      - uses: actions/checkout@master
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          #!/bin/bash

          MAX_FILE_SIZE=5000
          FAILED=0

          for F in ${{ steps.files.outputs.added_modified }}; do 
            echo "Checking file size: $F"
            size=$(du -k $F | cut -f1)
            if [ $size -ge $MAX_FILE_SIZE ]; then
              FAILED=1
              echo "ERROR: $F exceeds maximum file size."
            fi
          done

          if [ $FAILED -ne 0 ]; then
            exit -1
          fi;
